// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhhcqyopfqvrdmzemedv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoaGNxeW9wZnF2cmRtemVtZWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTE1OTAsImV4cCI6MjA2Mzc2NzU5MH0.rLsoPG5L_-YzptQehVm4fjmeseG8_T08DNkbjUV6CaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);